name: Automatic Update
run-name: Annotate new line in data files

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: "45 23 * * *" # run at 23:45 every day (will pick the date of that day yet)

jobs:
  edit-and-upload-rain-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Add new line
        run: |
          # 4 is the line number to add the new line
          sed "4 i $(date +%d/%m/%Y);0" src/data/pluviometro-1.txt > rain-data.tmp
          mv rain-data.tmp src/data/pluviometro-1.txt
          sed "4 i $(date +%d/%m/%Y);0" src/data/pluviometro-2.txt > rain-data.tmp
          mv rain-data.tmp src/data/pluviometro-2.txt
      - name: Commit and push
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'jaimemartinmartin15@users.noreply.github.com'
          git commit -am "Automatic update data files"
          git push
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-2
      - name: Upload files
        run: |
          aws --version
          aws s3 cp src/data/pluviometro-1.txt s3://lluvias.jaimeelingeniero.es/data/pluviometro-1.txt
          aws s3 cp src/data/pluviometro-2.txt s3://lluvias.jaimeelingeniero.es/data/pluviometro-2.txt
